services:

  mysql:
    container_name: mySQL
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: shop
      MYSQL_USER: root
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - mynet

  backend:
    container_name: backend
    image: "api1.0"
    ports:
      - 8080:8080
    restart: always
    environment:
      DB_URL: jdbc:mysql://mysql:3306/shop
      DB_PASSWORD: 1234
      DB_USER: root
    depends_on:
      - mysql
    networks:
      - mynet


networks:
  mynet:
    driver: bridge

