services:

  mysql:
    container_name: mySQL
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: shop
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - mynet

  backend:
    container_name: backend
    image: "api1.0"
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mysql
    networks:
      - mynet


networks:
  mynet:
    driver: bridge

